from pathlib import Path
from .base import BaseTemplate


class NextJSAppTemplate(BaseTemplate):
    name = "Next.js"
    language = "js"

    def get_dirs(self) -> list[str]:
        return [
            "app",
            "app/api",
            "components",
            "lib",
            "public",
            "styles",
        ]

    def get_files(self) -> dict[str, str]:
        return {
            "README.md": f"# {self.project_name}\n\nA Next.js App Router project.\n",
            ".gitignore": (
                "node_modules/\n.next/\nout/\n.env\n.env.local\n*.log\n.DS_Store\n"
            ),
            ".env.local.example": "NEXT_PUBLIC_APP_NAME={}\n".format(self.project_name),
            "app/layout.jsx": (
                'import "../styles/globals.css";\n\n'
                "export const metadata = {\n"
                f'  title: "{self.project_name}",\n'
                f'  description: "Generated by Spawn",\n'
                "};\n\n"
                "export default function RootLayout({ children }) {\n"
                "  return (\n"
                '    <html lang="en">\n'
                "      <body>{children}</body>\n"
                "    </html>\n"
                "  );\n"
                "}\n"
            ),
            "app/page.jsx": (
                "export default function Home() {\n"
                "  return (\n"
                "    <main>\n"
                f"      <h1>{self.project_name}</h1>\n"
                "    </main>\n"
                "  );\n"
                "}\n"
            ),
            "app/api/hello/route.js": (
                'import { NextResponse } from "next/server";\n\n'
                "export async function GET() {\n"
                '  return NextResponse.json({ message: "Hello from {}!" });\n'.format(
                    self.project_name
                )
                + "}\n"
            ),
            "styles/globals.css": (
                "* {\n"
                "  margin: 0;\n"
                "  padding: 0;\n"
                "  box-sizing: border-box;\n"
                "}\n\n"
                "body {\n"
                "  font-family: sans-serif;\n"
                "}\n"
            ),
            "next.config.js": (
                "/** @type {import('next').NextConfig} */\n"
                "const nextConfig = {};\n\n"
                "module.exports = nextConfig;\n"
            ),
            "components/.gitkeep": "",
            "lib/.gitkeep": "",
        }
